#!/bin/sh
# version 1.0  License: GPL 2.0
# author: chenwumail@gmail.com 2018

if [ "x${SM_DIR}" = "x" ]; then
  SM_DIR=${HOME}/sm #default svc dir is /home/{work}/sm
fi

read_ini () {
  file=$1;section=$2;item=$3;
  val=$(awk -F '=' '/\['${section}'\]/{a=1} (a==1 && "'${item}'"==$1){print}' ${file}) 
  echo ${val#*=}
}
usage() {
  echo "SM_DIR=${SM_DIR}"
  echo "usage: sm <r|run|start>|<k|kill|stop>|<re|restart> <service-name>"
  echo "       sm <run-all>|<kill-all>"
  echo "       sm <s|status> [<service-name>]"
  echo "       sm <e|enable>|<d|disable> <service-name>"
  echo "       sm <l|list>"
  echo "       sm <exec> <service-name>"
  echo "       sm <init>"
  echo "Service Manager (sm) Manual:"
  echo "  \${SM_DIR}/user/ -- *.service files, defined by user"
  echo "  \${SM_DIR}/work/ -- symbol link of *.service, it created or deleted by <enable> and <disable> command",
  echo "                    prohibit manually work in this dir for will be removed automaticlly."
  echo "  \${SM_DIR}/pid/ -- *.pid files, auto generated"
  echo "  \${SM_DIR}/log/ -- *.log files, auto generated"
  echo "  service file format:"
  echo "    [Service]"
  echo "    ExecStart=<command> [arguments]  -- ONLY ABSOLUTE PATH SUPPORTED."
  echo "    WorkingDirectory= -- OPTIONAL, ABSOLUTE PATH, default is ${SM_DIR} when not set"
  echo "Restart service when crash: "
  echo "  (1) sm enable sm-monitor"
  echo "  (2) sm run sm-monitor"
  echo "  (3) add Restart=always to foo.service"
  echo "  if foo crash, sm-monitor while restart it, checked every 5 minutes."
  echo "  don't worry about sm stop <service-name>, it will not be restart automaticlly."
}

############### svc main ##################
sm_cmd=$1
sm_name=$2
if [ "x${sm_cmd}" = "x" ]; then
  usage
  exit 1
fi

sm_dir=""
sm_short_name=${sm_name#*/}
if [ ! $sm_name = $sm_short_name ]; then
  sm_dir=${sm_name%/*}
fi

ECHO="echo -e"
os=`uname`
if [ "${os}" = "Darwin" ]; then
  ECHO="echo"
fi

IGNORE_SUBDIR="nosub"

case $sm_cmd in
  # one initilize command, careful for SM_DIR, default is ${HOME}/app
  init)
    echo "SM_DIR=${SM_DIR}"
    test -d ${SM_DIR}/user || mkdir -p ${SM_DIR}/user
    test -d ${SM_DIR}/work || mkdir -p ${SM_DIR}/work
    test -d ${SM_DIR}/pid  || mkdir -p ${SM_DIR}/pid
    test -d ${SM_DIR}/log  || mkdir -p ${SM_DIR}/log
    echo "[Service]" > ${SM_DIR}/user/sm-monitor.service
    echo "ExecStart=/usr/bin/sm monitor" >> ${SM_DIR}/user/sm-monitor.service
    sm enable sm-monitor
    ;;  
  # two command for app service in user directory
  l)
    applist=$(ls ${SM_DIR}/user/)
    for app in $applist
    do
      name=${app%%.*}
      /bin/echo -n "$name "
    done
    echo ""
    ;;
  list)
    applist=$(ls ${SM_DIR}/user/)
    for app in $applist
    do
      name=${app%%.*}
      daemon=$(read_ini ${SM_DIR}/user/${name}.service Service ExecStart)
      echo "$name -- $daemon"
    done
    ;;
  # one exec command, foregroud execute service in user directory
  exec)
    if [ "x${sm_name}" = "x" ]; then
      usage
      exit 1
    fi  
    echo "exec $sm_name ..."
    daemon=$(read_ini ${SM_DIR}/user/${sm_short_name}.service Service ExecStart) 
    echo $daemon
    $daemon
    ;;
  # two command to create or remove symbol link from user directory to work directory
  e|enable)
    if [[ -n "${sm_dir}" && ! -d ${SM_DIR}/work/${sm_dir} ]]; then
      mkdir -p ${SM_DIR}/work/${sm_dir}
      mkdir -p ${SM_DIR}/pid/${sm_dir}
      mkdir -p ${SM_DIR}/log/${sm_dir}
    fi
    if [ -f ${SM_DIR}/user/${sm_short_name}.service ]; then
      ln -sf ${SM_DIR}/user/${sm_short_name}.service ${SM_DIR}/work/${sm_name}.service
    else
      echo "warning, ${sm_name} not found."
      exit 1
    fi
    ;;
  d|disable)
    if [ -f ${SM_DIR}/work/${sm_name}.service ]; then
      rm ${SM_DIR}/work/${sm_name}.service
    else
      echo "warning, ${sm_name} not found."
      exit 1
    fi
    ;;    
  # two all commands, batch do something
  run-all|start-all)
    if [[ "x${sm_name}" = "x" || "x${sm_name}" = "x${IGNORE_SUBDIR}" ]]; then
      applist=$(ls ${SM_DIR}/work/)
      for app in $applist
      do
        name=${app%%.*}
        if [ -d ${SM_DIR}/work/${name} ]; then
          if [ ! "x${sm_name}" = "x${IGNORE_SUBDIR}" ]; then
            sm run-all $name
          fi
        else
          sm run $name
        fi
      done
      exit 0
    fi
    if [[ -n "${sm_name}" && -d ${SM_DIR}/work/${sm_name}  ]]; then # sm_name is dir name
      subapplist=$(ls ${SM_DIR}/work/${sm_name})
      for sub in $subapplist
      do
        subname=${sub%%.*}
        sm run ${sm_name}/${subname}
      done
      exit 0
    fi
    ;;
  kill-all|stop-all)
    if [[ "x${sm_name}" = "x" || "x${sm_name}" = "x${IGNORE_SUBDIR}" ]]; then
      applist=$(ls ${SM_DIR}/work/)
      for app in $applist
      do
        name=${app%%.*}
        if [ -d ${SM_DIR}/work/${name} ]; then
          if [ ! "x${sm_name}" = "x${IGNORE_SUBDIR}" ]; then
            sm kill-all $name
          fi
        else
          if [ ! "${name}" = "sm-monitor" ]; then
            sm kill $name
          fi
        fi
      done
      exit 0
    fi
    if [[ -n "${sm_name}" && -d ${SM_DIR}/work/${sm_name}  ]]; then # sm_name is dir name
      subapplist=$(ls ${SM_DIR}/work/${sm_name})
      for sub in $subapplist
      do
        subname=${sub%%.*}
        sm kill ${sm_name}/${subname}
      done
      exit 0
    fi
    ;;
  r|run|start)
    if [ "x${sm_name}" = "x" ]; then
      usage
      exit 1
    fi
    last_pid=`test -f ${SM_DIR}/pid/${sm_name}.pid && cat ${SM_DIR}/pid/${sm_name}.pid` || last_pid=-1
    ps -p $last_pid > /dev/null 2>&1
    status=$?
    if [ $status -eq 0 ]; then
      $ECHO "\033[32m active (running) \033[0m  $sm_name"
      ps -f -p $last_pid
      $ECHO "\033[33m warning \033[0m $sm_name already running."
      exit 0
    fi    
    echo "start $sm_name ..."
    daemon=$(read_ini ${SM_DIR}/work/${sm_name}.service Service ExecStart)
    workdir=$(read_ini ${SM_DIR}/work/${sm_name}.service Service WorkingDirectory)
    if [ "x${workdir}" = "x" ]; then
      workdir=${SM_DIR}
    fi
    echo $daemon
    cd $workdir
    $daemon > ${SM_DIR}/log/${sm_name}.log 2>&1 &
    pid=$!
    cd -
    echo $pid > ${SM_DIR}/pid/${sm_name}.pid
    echo "started, pid = ${pid}."
    ;;
  re|restart)
    sm stop $sm_name
    sleep 3
    sm start $sm_name
    ;;
  monitor) # don't run it manaully, run by "sm run sm-monitor".
    while true
    do
      sleep 300
      sm monitor-always
    done
    ;;
  monitor-always) # don't run it manaully, it will called by monitor command.
    applist=$(ls ${SM_DIR}/work/)
    for app in $applist
    do
      name=${app%%.*}
      always=$(read_ini ${SM_DIR}/work/${name}.service Service Restart)
      if [ "x${always}" = "xalways" ]; then
        if [ -f ${SM_DIR}/pid/${name}.pid ]; then

          last_pid=`test -f ${SM_DIR}/pid/${name}.pid && cat ${SM_DIR}/pid/${name}.pid` || last_pid=-1
          ps -p $last_pid > /dev/null 2>&1
          status=$?
          if [ $status -eq 0 ]; then
            echo $name > /dev/null
          else
            echo "start crashed process."
            sm run $name   
          fi

        fi # else no pid file,ignore
      fi # else not always restart, ignore
    done    
    ;;     
  k|kill|stop)
    if [ "x${sm_name}" = "x" ]; then
      usage
      exit 1
    fi
    last_pid=`test -f ${SM_DIR}/pid/${sm_name}.pid && cat ${SM_DIR}/pid/${sm_name}.pid` || exit 2
    ps -p $last_pid > /dev/null 2>&1
    status=$?
    if [ $status -ne 0 ]; then
      echo "(pid=${last_pid}) No such process"
      test -f ${SM_DIR}/pid/${sm_name}.pid && rm ${SM_DIR}/pid/${sm_name}.pid
      exit 3
    fi
    echo "stop $sm_name (pid=${last_pid}) ... "
    if [ $last_pid -gt 0 ]; then
      kill -9 $last_pid && rm ${SM_DIR}/pid/${sm_name}.pid
    else
      echo "unknow error to stop"
      exit 4
    fi
    ;;
  s|status)
    if [ "x${sm_name}" = "x" ]; then
      applist=$(ls ${SM_DIR}/work/)
      for app in $applist
      do
        name=${app%%.*}
        sm ${sm_cmd} ${name}
      done
      exit 0
    fi
    if [ "x${sm_name}" = "x${IGNORE_SUBDIR}" ]; then
      applist=$(ls ${SM_DIR}/work/)
      for app in $applist
      do
        name=${app%%.*}
        if [ ! -d ${SM_DIR}/work/${name} ]; then # skip sub dir
          sm ${sm_cmd} ${name}
        fi
      done
      exit 0
    fi    
    if [ -d ${SM_DIR}/work/${sm_name} ]; then
      subapplist=$(ls ${SM_DIR}/work/${sm_name}/)
      for sub in $subapplist
      do
        sub_name=${sub%%.*}
        sm ${sm_cmd} ${sm_name}/$sub_name
      done
      exit 0
    fi
    if [ ! -f ${SM_DIR}/work/${sm_name}.service ]; then
      echo "${sm_name} not found." 
      exit 9
    fi
    last_pid=`test -f ${SM_DIR}/pid/${sm_name}.pid && cat ${SM_DIR}/pid/${sm_name}.pid` || last_pid=-1
    ps -p $last_pid > /dev/null 2>&1
    status=$?
    cmd_line=""
    if [ $status -eq 0 ]; then
      if [ ${sm_cmd} = "status" ]; then
        line=`ps -f -p $last_pid | tail -n 1`
        cmd_line="/${line#*/}"
      fi
      $ECHO "\033[32m active (running) \033[0m [$sm_name] -- $last_pid ${cmd_line}"
    else
      if [ ${sm_cmd} = "status" ]; then
        cmd_line="-- $(read_ini ${SM_DIR}/work/${sm_name}.service Service ExecStart)"
      fi
      $ECHO "\033[31m inactive \033[0m [$sm_name] ${cmd_line}"
    fi
    ;;
  log)
    if [ "x${sm_name}" = "x" ]; then
      usage
      exit 1
    fi
    if [ -f ${SM_DIR}/log/${sm_name}.log ]; then
      tail -n 100 ${SM_DIR}/log/${sm_name}.log
    else
      echo "log file ${SM_DIR}/log/${sm_name}.log not found."
      exit 9
    fi
    ;;   
  *)
    echo "unknown command: $sm_cmd"
    usage
    ;;
esac

############### svc main end ################